import { useState, useEffect, useRef } from "react";
import {
  BookOpen,
  Sparkles,
  ChevronRight,
  GraduationCap,
  Zap,
} from "lucide-react";
import Markdown from "react-markdown";

export function CryptoMasterclass() {
  const [topic, setTopic] = useState("Trading Basics");
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [liveMarketData, setLiveMarketData] = useState<any>(null);

  const autoGenerated = useRef(false);

  const topics = [
    "Trading Basics",
    "Blockchain Technology",
    "Market Analysis",
    "DeFi Ecosystem",
    "Risk Management",
  ];

  const fetchLiveMarketData = async () => {
    try {
      const res = await fetch("https://api.binance.com/api/v3/ticker/24hr");
      const data = await res.json();
      setLiveMarketData(data);
      // Auto-generate content using the new live data if it's already selected
      if (topic) {
        generateContent(topic, data);
      }
    } catch (e) {
      console.error("CryptoMasterclass live fetch failed", e);
    }
  };

  useEffect(() => {
    fetchLiveMarketData();
    const interval = setInterval(() => {
      fetchLiveMarketData();
    }, 3600000); // Update every 1 hour
    return () => clearInterval(interval);
  }, []); // Run on mount

  const generateContent = async (
    selectedTopic: string,
    marketData: any = liveMarketData,
  ) => {
    setLoading(true);
    try {
      await new Promise((r) => setTimeout(r, 1200)); // Simulate generation

      let liveContext = "";
      if (marketData && marketData.length > 0) {
        let btc = marketData.find((t: any) => t.symbol === "BTCUSDT");
        let eth = marketData.find((t: any) => t.symbol === "ETHUSDT");
        if (btc && eth) {
          liveContext = `
> ⚡ **Live Market Intel:** BTC is currently trading at $${parseFloat(btc.lastPrice).toLocaleString(undefined, { maximumFractionDigits: 0 })} (${parseFloat(btc.priceChangePercent) > 0 ? "+" : ""}${parseFloat(btc.priceChangePercent).toFixed(2)}% in 24h). ETH is at $${parseFloat(eth.lastPrice).toLocaleString(undefined, { maximumFractionDigits: 0 })}. Keep these live figures in mind as you study the concepts below.`;
        }
      }

      const simulatedData: Record<string, string> = {
        "Trading Basics": `## Mastering Trading Basics
${liveContext}

Welcome to the foundation of crypto trading. Here we cover the absolute essentials you need before deploying capital.

### 1. Market Orders vs Limit Orders
- **Market Order:** Buy or sell immediately at the best available current price. Use this when speed is more important than the exact price.
- **Limit Order:** Buy or sell at a specific price or better. Use this to control your entry and exit points precisely.

### 2. Candlestick Anatomy
Candle bodies show the open and close, while the wicks (shadows) show the high and low of that period. A green candle means the close was higher than the open.

### 3. Support and Resistance
- **Support:** A price level where a downtrend tends to pause due to a concentration of demand.
- **Resistance:** A price level where an uptrend tends to pause due to a concentration of supply.`,
        "Blockchain Technology": `## Understanding Blockchain Technology
${liveContext}

The underlying architecture powering cryptocurrencies.

### Decentralized Ledgers
At its core, a blockchain is a distributed database that is shared among the nodes of a computer network. 

### Cryptographic Hashing
Blocks are securely linked using cryptographic hashes. Once data has been recorded in a given block, it cannot be altered retroactively without the alteration of all subsequent blocks.

### Consensus Mechanisms
- **Proof of Work (PoW):** Requires computational energy (mining). E.g., Bitcoin.
- **Proof of Stake (PoS):** Validators lock capital to secure the network. E.g., Ethereum.`,
        "Market Analysis": `## Deep Dive: Market Analysis
${liveContext}

To anticipate market movements, you need to combine different analysis methods.

### Fundamental Analysis (FA)
Evaluating the intrinsic value of an asset. Look at the tokenomics, team, use cases, regulatory environment, and on-chain metrics (active addresses, transaction volume).

### Technical Analysis (TA)
Statistical trends gathered from trading activity, such as price movement and volume.
* **Moving Averages (MA):** Smooths out price data.
* **RSI (Relative Strength Index):** Measures momentum (oversold vs overbought).

### Sentiment Analysis
Gauging the mood of the market. Often measured through social volume or the Fear & Greed Index.`,
      };

      const defaultContent = `## ${selectedTopic}\n${liveContext}\n\nThis is an accelerated learning module for **${selectedTopic}**.\n\n### Core Concepts\n* Topic introduction and historical context.\n* Key mechanisms and structural overview.\n* Best practices and modern applications.\n\nKeep reviewing your curriculum to master these elements.`;

      setContent(simulatedData[selectedTopic] || defaultContent);
      autoGenerated.current = true;
    } catch (err: any) {
      setContent("Module generation failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // Automatically load the first module if content is empty when live data loads
  useEffect(() => {
    if (liveMarketData && !content && !loading && !autoGenerated.current) {
      generateContent(topic, liveMarketData);
    }
  }, [liveMarketData, content, loading, topic]);

  return (
    <div className="bg-[#131722] border border-[#2A2E39] rounded-2xl p-6 flex flex-col h-full relative overflow-hidden">
      {/* Background Graphic */}
      <div className="absolute top-0 right-0 p-8 opacity-[0.03] pointer-events-none">
        <GraduationCap className="w-64 h-64" />
      </div>

      <div className="flex items-center justify-between mb-6 relative z-10 w-full">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-blue-500/10 rounded-xl">
            <BookOpen className="w-5 h-5 text-blue-400" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white tracking-tight flex items-center gap-2">
              Crypto Masterclass
              <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 ml-2">
                <div className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse"></div>
                <span className="text-[9px] font-bold text-blue-500 uppercase tracking-wider">
                  Live Tracker Active
                </span>
              </div>
            </h2>
            <p className="text-xs text-[#787B86] font-mono mt-0.5">
              AI-Powered Education Hub with Real-Time Data
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 relative z-10">
        <div className="md:col-span-1 flex flex-col gap-2">
          <h3 className="text-[10px] uppercase font-bold tracking-widest text-white/40 mb-2">
            Curriculum
          </h3>
          {topics.map((t) => (
            <button
              key={t}
              onClick={() => {
                setTopic(t);
                generateContent(t, liveMarketData);
              }}
              className={`p-3 text-left rounded-xl border text-sm transition-all focus:outline-none focus:ring-1 focus:ring-blue-500/50 flex justify-between items-center ${
                topic === t
                  ? "border-blue-500/30 bg-blue-500/10 text-blue-400 shadow-[0_0_15px_rgba(59,130,246,0.1)]"
                  : "border-[#2A2E39] bg-[#1E222D] text-[#787B86] hover:bg-[#1E222D]"
              }`}
            >
              <span className="font-medium">{t}</span>
              {topic === t && <ChevronRight className="w-4 h-4" />}
            </button>
          ))}
          {!content && !loading && (
            <div className="mt-4 p-4 rounded-xl border border-[#2A2E39] bg-[#1E222D] text-xs text-[#787B86] text-center flex flex-col items-center gap-2">
              <Sparkles className="w-5 h-5 opacity-50" />
              Select a topic to generate your personalized AI masterclass
              module.
            </div>
          )}
        </div>

        <div className="md:col-span-3 min-h-[300px] border border-[#2A2E39] rounded-xl bg-[#1E222D] p-6 flex flex-col">
          {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center gap-4 text-white/40">
              <Sparkles className="w-8 h-8 animate-pulse text-blue-400/50" />
              <div className="text-sm font-mono animate-pulse text-center">
                Synthesizing {topic} Module with Live Context...
              </div>
            </div>
          ) : content ? (
            <div className="prose prose-invert prose-sm max-w-none prose-headings:text-[#B2B5BE] prose-p:text-[#787B86] prose-blockquote:border-l-blue-500 prose-blockquote:bg-blue-500/5 prose-blockquote:px-4 prose-blockquote:py-1 prose-blockquote:rounded-r-lg prose-blockquote:text-blue-200 prose-a:text-blue-400 overflow-y-auto max-h-[500px] custom-scrollbar pr-4">
              <div className="markdown-body">
                <Markdown>{content}</Markdown>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center gap-4 opacity-30">
              <BookOpen className="w-12 h-12" />
              <span className="text-sm font-mono">Module Content Area</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
